version: "3.3"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_ENDPOINT: "http://minio:9000"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_DB: dev-mem
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KEYCLOAK_SERVER_URL: "http://keycloak:8080"
    command: start-dev

  app:
    build:
      context: .
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - minio
      - keycloak

volumes:
  minio_data:
