version: '3.9'
services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs-server
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - C:\Users\Nikola\Documents\Kursova_Rabota_VoT\nfs:/data
    ports:
      - "2049:2049"
    cap_add:
      - SYS_ADMIN
    privileged: true 

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev

  app:
    build:
      context: ./app
    container_name: file-app
    ports:
      - "5000:5000"
    environment:
      - NFS_PATH=/mnt/nfs
      - KEYCLOAK_URL=http://keycloak:8080
    volumes:
      - ./nfs:/mnt/nfs
    depends_on:
      - nfs-server
      - keycloak
